default_bit = 4096
distinguished_name = req_distinguished_name
prompt = no

[req_distinguished_name]
# countryName                     = Country Name (2 letter code)
# countryName_default             = CN
# countryName_min                 = 2
# countryName_max                 = 2
# stateOrProvinceName             = State or Province Name (full name) ## Print this message
# stateOrProvinceName_default     = HeNan ## This is the default value
# localityName                    = Locality Name (eg, city) ## Print this message
# localityName_default            = ZhengZhou ## This is the default value
# 0.organizationName              = Organization Name (eg, company) ## Print this message
# 0.organizationName_default      = FreeNet ## This is the default value
# organizationalUnitName          = Organizational Unit Name (eg, section) ## Print this message
# organizationalUnitName_default  = Admin ## This is the default value
# commonName                      = Common Name (eg, your name or your server hostname) ## Print this message
# commonName_default              = CA ## This is the default value
# commonName_max                  = 64
# emailAddress                    = Email Address ## Print this message
# emailAddress_default            = jackadam@sina.com  ## This is the default value
# emailAddress_max                = 64