version: '3.1'
services:
    samba:
        image: jackadam/samba
        container_name: samba
        privileged: true
        restart: always
        ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139"
        - "445:445"
        volumes:
        - /Storage/data/share:/share