version: '3.8'
services:
    aria2:
        image: cuteribs/aria2
        container_name: aria2
        privileged: true
        restart: always
        ports:
        - "8080:80"
        - "6800:6800"
        environment:
            Secret： /run/secrets/aria2_password
        volumes:
        - ./download:/data/download
        secrets:
            - aria2_password
secrets:
   aria2_password:
     file: .password.txt