FROM ocsinventory/ocsinventory-docker-image:2.6

COPY OCSNG_UNIX_SERVER_2.7.tar.gz /tmp/OCSNG_UNIX_SERVER_2.7.tar.gz
COPY docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
COPY zh_CN.tar /tmp/zh_CN.tar