name: vaultwarden
services:
    server:
        container_name: vaultwarden
        volumes:
            - ./data/:/data/
        ports:
            - ${HTTP_PORT}:80
        image: vaultwarden/server:latest
        restart: always
        environment:
          ADMIN_TOKEN: ${ADMIN_TOKEN}
          SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
          INVITATIONS_ALLOWED: ${INVITATIONS_ALLOWED}
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN}`)" 
          - "traefik.http.routers.vaultwarden.entrypoints=websecure"
          - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
          - "traefik.http.routers.vaultwarden.tls.certresolver=${CERTIFICATE_MANAGER}"
networks:
  #未设置网络时，使用默认网络
  default:
    #自定义默认网络名
    name: ${NETWORK_NAME}
    # 使用外部网络
    external: true