version: "2"

services:
  server:
    #image: gitea/gitea:1.20.2-rootless
    image: gitea/gitea:latest-rootless
    restart: always
    privileged: true
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3090:3000"
      - "2222:2222"