version: '3'
services:
  onenav:
    image: 'helloz/onenav:latest'
    container_name: onenav
    ports:
      - "3080:80"
    volumes:
      - './data:/data/wwwroot/default/data'
    
    restart:
      always