name: onenav
services:
  onenav:
    image: 'helloz/onenav:latest'
    container_name: onenav
    restart: unless-stopped
    volumes:
      - './data:/data/wwwroot/default/data'
    ports:
      - '${HTTP_PORT}:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onenav.rule=Host(`${ONENAV_DOMAIN}`)"
      - "traefik.http.routers.onenav.entrypoints=websecure"
      - "traefik.http.routers.onenav.tls=true"
      - "traefik.http.routers.onenav.tls.certresolver=${CERT_RESOLVER_NAME}"

networks:
  #未设置网络时，使用默认网络
  default:
    #自定义默认网络名
    name: ${NETWORK_NAME}
    # 使用外部网络
    external: true

