version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--cleanup", "--rolling-restart", "--remove-volumes"]
        
