version: '3'

services:


  ocsdb :
    image : mysql:5.7
    container_name : ocsinventory-db
    restart: always
    ports :
      - 3306:3306
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
    networks:
      - localocs
  
networks:
  localocs:

volumes:
  perlcomdata:
  extensionsdata:
  varlibdata:
  httpdconfdata:
  sqldata:
  