version: "3" #版本3
services: #服务
  nginx:   #服务名
    image: nginx:stable-alpine   #镜像名称
    privileged: true  #高级权限
    tty: true         #开一个终端
    container_name: nginx  #自定义容器名
    restart: always
    ports:              #开放端口映射
        - 8087:8087
    volumes:
        - ./conf.d:/etc/nginx/conf.d #默认配置文件
        # - ./AriaNg-1.3.6:/airang   #aria2ng目录
        # - /storage/data/share:/download  #下载浏览目录

networks:
  default:
    external: true
    name: mynet