version: '3.5'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
            
        privileged: true