version: '3.5'

services:
    ssh:
        build:
            context: .
            dockerfile: ssh
        container_name: ssh
        restart: always
        ports:
            - "8022:22"
            
        privileged: true