version: '3'

services:

  ocsdb :
    image : mysql:5.7
    container_name : ocsdb
    restart: always
    ports :
      - 33060:3306
    volumes :
      - ./ocs/sql/:/docker-entrypoint-initdb.d/
      - ocs_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
    networks:
      - localocs
      
  glpidb:
    image: mysql:5.7
    container_name: glpidb
    hostname: glpidb
    privileged: true
    restart: always
    ports :
      - 33062:3306
    volumes:
      - glpi_db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD : diouxx
        MYSQL_DATABASE : glpidb
        MYSQL_USER : glpi_user
        MYSQL_PASSWORD : glpi
    restart: always
    networks:
      - localocs

  glpi:
    #image: diouxx/glpi
    build:
      context: ./glpi/
      dockerfile: glpiDockerfile
    container_name : glpi
    hostname: glpi
    privileged: true
    restart: always
    environment:
        - TIMEZONE=Asia/Shanghai
    ports:
      - "81:80"
    links:
      - glpidb
    networks:
      - localocs
    depends_on:
      - glpidb  

  ocs:
    #image: ocsinventory/ocsinventory-docker-image:2.7
    build:
      context: ./ocs/
      dockerfile: ocsDockerfile
    container_name : ocs
    hostname: ocs
    privileged: true
    restart: always
    ports:
      - 80:80
    volumes:
      - "perlcomdata:/etc/ocsinventory-server"
      - "extensionsdata:/usr/share/ocsinventory-reports/ocsreports/extensions"
      - "varlibdata:/var/lib/ocsinventory-reports"
      - "httpdconfdata:/etc/httpd/conf.d"
    environment:
      OCS_DB_SERVER: ocsdb
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      # See documentation to set up SSL for MySQL
      OCS_SSL_ENABLED: 0
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb  



  
networks:
  localocs:
volumes:
  perlcomdata:
  extensionsdata:
  varlibdata:
  httpdconfdata:
  glpi_db:
  ocs_db:
