services:
  server:
    image: jackadam/gitea-arm:1.23.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      # - ./gitea_data:/data
      # - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"