name: "Build Docker File"

on: 
  workflow_dispatch:
    inputs:
      project:
        description: 'GitHub project'
        default: ''
      dockerfile:
        description: 'Path to Dockerfile'
        required: true
        default: 'Dockerfile'
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
        
run-name: ${{ github.actor }} is testing build ${{ github.event.inputs.project }} 🚀

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.project || github.repository }}
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 docker
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Build and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.event.inputs.project || '.' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          file: ${{ github.event.inputs.dockerfile }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.project || github.repository }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.project || github.repository }}:${{ github.event.inputs.tag }}